name: Release Drafter

on:
  push:
    # branches to consider only for autosquash (optional)
    branches:
      - main
  # pull_request event is required only for autolabeler
  pull_request:
    types: [opened, reopened, synchronize]
  # pull_request_target event is required for autolabeler to support forks
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  update_release_draft:
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      # (Optional) Check out the repository
      # - uses: actions/checkout@v4
      # Drafts your next Release notes as Pull Requests are merged into "main"
      - uses: release-drafter/release-drafter@v6
        # (Optional) specify config name to use, default is .github/release-drafter.yml
        # with:
        #   config-name: my-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
